2018-05-31 11:47:49,672 ERROR: Exception on /table [GET] [in /Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/lucamaiano/Desktop/visualization/app/main/routes.py", line 34, in table
    return render_template('table.html', title='Measurements', measures=type(measures))
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/lucamaiano/Desktop/visualization/app/templates/table.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/lucamaiano/Desktop/visualization/app/templates/base.html", line 165, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/lucamaiano/Desktop/visualization/app/templates/table.html", line 27, in block "content"
    {{ measure.day }} <br>
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'measure' is undefined
2018-05-31 11:48:06,235 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 11:49:45,456 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 11:50:32,704 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 11:51:12,769 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 11:53:02,892 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 11:53:04,904 ERROR: Exception on /table [GET] [in /Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lucamaiano/miniconda3/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/lucamaiano/Desktop/visualization/app/main/routes.py", line 35, in table
    print(measures[m])
TypeError: list indices must be integers or slices, not Measurements
2018-05-31 11:53:19,968 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 11:56:20,614 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 11:57:52,219 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 11:59:01,431 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 12:00:23,237 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 12:00:59,450 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 12:01:53,906 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 12:54:07,026 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 12:54:46,052 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 12:55:05,952 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 12:57:02,611 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 12:58:56,748 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 13:08:08,775 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 13:09:13,083 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 13:10:22,558 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 13:11:01,469 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 13:11:30,691 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 13:28:14,177 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:01:46,177 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:03:35,052 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:13:07,899 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:17:28,453 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:17:55,882 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:20:16,156 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:21:27,831 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:22:03,361 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:23:08,463 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:24:42,892 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:38:29,620 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:40:51,630 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:41:04,969 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:44:42,829 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:50:04,784 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:50:21,176 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:57:05,990 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 14:58:13,044 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 15:02:59,709 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 15:04:36,259 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 15:05:01,648 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 15:08:39,253 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 15:09:32,764 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 15:11:50,870 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 15:13:20,144 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 15:14:07,656 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 15:15:31,797 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
2018-05-31 15:16:53,111 INFO: Lung System startup [in /Users/lucamaiano/Desktop/visualization/app/__init__.py:46]
